webpackJsonp([82969914521642],{3370:function(e,r){e.exports={pathContext:{docHtml:"<h1>verror: rich JavaScript errors</h1>\n<p>This module provides several classes in support of Joyent's <a href=\"http://www.joyent.com/developers/node/design/errors\">Best Practices for\nError Handling in Node.js</a>.\nIf you find any of the behavior here confusing or surprising, check out that\ndocument first.</p>\n<p>The error classes here support:</p>\n<ul>\n<li>printf-style arguments for the message</li>\n<li>chains of causes</li>\n<li>properties to provide extra information about the error</li>\n<li>creating your own subclasses that support all of these</li>\n</ul>\n<p>The classes here are:</p>\n<ul>\n<li><strong>VError</strong>, for chaining errors while preserving each one's error message.\nThis is useful in servers and command-line utilities when you want to\npropagate an error up a call stack, but allow various levels to add their own\ncontext.  See examples below.</li>\n<li><strong>WError</strong>, for wrapping errors while hiding the lower-level messages from the\ntop-level error.  This is useful for API endpoints where you don't want to\nexpose internal error messages, but you still want to preserve the error chain\nfor logging and debugging.</li>\n<li><strong>SError</strong>, which is just like VError but interprets printf-style arguments\nmore strictly.</li>\n<li><strong>MultiError</strong>, which is just an Error that encapsulates one or more other\nerrors.  (This is used for parallel operations that return several errors.)</li>\n</ul>\n<h1>Quick start</h1>\n<p>First, install the package:</p>\n<pre><code>npm install verror\n</code></pre>\n<p>If nothing else, you can use VError as a drop-in replacement for the built-in\nJavaScript Error class, with the addition of printf-style messages:</p>\n<pre><code class=\"language-javascript\">var err = new VError('missing file: \"%s\"', '/etc/passwd');\nconsole.log(err.message);\n</code></pre>\n<p>This prints:</p>\n<pre><code>missing file: \"/etc/passwd\"\n</code></pre>\n<p>You can also pass a <code>cause</code> argument, which is any other Error object:</p>\n<pre><code class=\"language-javascript\">var fs = require('fs');\nvar filename = '/nonexistent';\nfs.stat(filename, function (err1) {\n    var err2 = new VError(err1, 'stat \"%s\"', filename);\n    console.error(err2.message);\n});\n</code></pre>\n<p>This prints out:</p>\n<pre><code>stat \"/nonexistent\": ENOENT, stat '/nonexistent'\n</code></pre>\n<p>which resembles how Unix programs typically report errors:</p>\n<pre><code>$ sort /nonexistent\nsort: open failed: /nonexistent: No such file or directory\n</code></pre>\n<p>To match the Unixy feel, when you print out the error, just prepend the\nprogram's name to the VError's <code>message</code>.  Or just call\n<a href=\"https://github.com/joyent/node-cmdutil\">node-cmdutil.fail(your_verror)</a>, which\ndoes this for you.</p>\n<p>You can get the next-level Error using <code>err.cause()</code>:</p>\n<pre><code class=\"language-javascript\">console.error(err2.cause().message);\n</code></pre>\n<p>prints:</p>\n<pre><code>ENOENT, stat '/nonexistent'\n</code></pre>\n<p>Of course, you can chain these as many times as you want, and it works with any\nkind of Error:</p>\n<pre><code class=\"language-javascript\">var err1 = new Error('No such file or directory');\nvar err2 = new VError(err1, 'failed to stat \"%s\"', '/junk');\nvar err3 = new VError(err2, 'request failed');\nconsole.error(err3.message);\n</code></pre>\n<p>This prints:</p>\n<pre><code>request failed: failed to stat \"/junk\": No such file or directory\n</code></pre>\n<p>The idea is that each layer in the stack annotates the error with a description\nof what it was doing.  The end result is a message that explains what happened\nat each level.</p>\n<p>You can also decorate Error objects with additional information so that callers\ncan not only handle each kind of error differently, but also construct their own\nerror messages (e.g., to localize them, format them, group them by type, and so\non).  See the example below.</p>\n<h1>Deeper dive</h1>\n<p>The two main goals for VError are:</p>\n<ul>\n<li><strong>Make it easy to construct clear, complete error messages intended for\npeople.</strong>  Clear error messages greatly improve both user experience and\ndebuggability, so we wanted to make it easy to build them.  That's why the\nconstructor takes printf-style arguments.</li>\n<li><strong>Make it easy to construct objects with programmatically-accessible\nmetadata</strong> (which we call <em>informational properties</em>).  Instead of just saying\n\"connection refused while connecting to 192.168.1.2:80\", you can add\nproperties like <code>\"ip\": \"192.168.1.2\"</code> and <code>\"tcpPort\": 80</code>.  This can be used\nfor feeding into monitoring systems, analyzing large numbers of Errors (as\nfrom a log file), or localizing error messages.</li>\n</ul>\n<p>To really make this useful, it also needs to be easy to compose Errors:\nhigher-level code should be able to augment the Errors reported by lower-level\ncode to provide a more complete description of what happened.  Instead of saying\n\"connection refused\", you can say \"operation X failed: connection refused\".\nThat's why VError supports <code>causes</code>.</p>\n<p>In order for all this to work, programmers need to know that it's generally safe\nto wrap lower-level Errors with higher-level ones.  If you have existing code\nthat handles Errors produced by a library, you should be able to wrap those\nErrors with a VError to add information without breaking the error handling\ncode.  There are two obvious ways that this could break such consumers:</p>\n<ul>\n<li>The error's name might change.  People typically use <code>name</code> to determine what\nkind of Error they've got.  To ensure compatibility, you can create VErrors\nwith custom names, but this approach isn't great because it prevents you from\nrepresenting complex failures.  For this reason, VError provides\n<code>findCauseByName</code>, which essentially asks: does this Error <em>or any of its\ncauses</em> have this specific type?  If error handling code uses\n<code>findCauseByName</code>, then subsystems can construct very specific causal chains\nfor debuggability and still let people handle simple cases easily.  There's an\nexample below.</li>\n<li>The error's properties might change.  People often hang additional properties\noff of Error objects.  If we wrap an existing Error in a new Error, those\nproperties would be lost unless we copied them.  But there are a variety of\nboth standard and non-standard Error properties that should <em>not</em> be copied in\nthis way: most obviously <code>name</code>, <code>message</code>, and <code>stack</code>, but also <code>fileName</code>,\n<code>lineNumber</code>, and a few others.  Plus, it's useful for some Error subclasses\nto have their own private properties -- and there'd be no way to know whether\nthese should be copied.  For these reasons, VError first-classes these\ninformation properties.  You have to provide them in the constructor, you can\nonly fetch them with the <code>info()</code> function, and VError takes care of making\nsure properties from causes wind up in the <code>info()</code> output.</li>\n</ul>\n<p>Let's put this all together with an example from the node-fast RPC library.\nnode-fast implements a simple RPC protocol for Node programs.  There's a server\nand client interface, and clients make RPC requests to servers.  Let's say the\nserver fails with an UnauthorizedError with message \"user 'bob' is not\nauthorized\".  The client wraps all server errors with a FastServerError.  The\nclient also wraps all request errors with a FastRequestError that includes the\nname of the RPC call being made.  The result of this failed RPC might look like\nthis:</p>\n<pre><code>name: FastRequestError\nmessage: \"request failed: server error: user 'bob' is not authorized\"\nrpcMsgid: &#x3C;unique identifier for this request>\nrpcMethod: GetObject\ncause:\n    name: FastServerError\n    message: \"server error: user 'bob' is not authorized\"\n    cause:\n        name: UnauthorizedError\n        message: \"user 'bob' is not authorized\"\n        rpcUser: \"bob\"\n</code></pre>\n<p>When the caller uses <code>VError.info()</code>, the information properties are collapsed\nso that it looks like this:</p>\n<pre><code>message: \"request failed: server error: user 'bob' is not authorized\"\nrpcMsgid: &#x3C;unique identifier for this request>\nrpcMethod: GetObject\nrpcUser: \"bob\"\n</code></pre>\n<p>Taking this apart:</p>\n<ul>\n<li>The error's message is a complete description of the problem.  The caller can\nreport this directly to its caller, which can potentially make its way back to\nan end user (if appropriate).  It can also be logged.</li>\n<li>The caller can tell that the request failed on the server, rather than as a\nresult of a client problem (e.g., failure to serialize the request), a\ntransport problem (e.g., failure to connect to the server), or something else\n(e.g., a timeout).  They do this using <code>findCauseByName('FastServerError')</code>\nrather than checking the <code>name</code> field directly.</li>\n<li>If the caller logs this error, the logs can be analyzed to aggregate\nerrors by cause, by RPC method name, by user, or whatever.  Or the\nerror can be correlated with other events for the same rpcMsgid.</li>\n<li>It wasn't very hard for any part of the code to contribute to this Error.\nEach part of the stack has just a few lines to provide exactly what it knows,\nwith very little boilerplate.</li>\n</ul>\n<p>It's not expected that you'd use these complex forms all the time.  Despite\nsupporting the complex case above, you can still just do:</p>\n<p>   new VError(\"my service isn't working\");</p>\n<p>for the simple cases.</p>\n<h1>Reference: VError, WError, SError</h1>\n<p>VError, WError, and SError are convenient drop-in replacements for <code>Error</code> that\nsupport printf-style arguments, first-class causes, informational properties,\nand other useful features.</p>\n<h2>Constructors</h2>\n<p>The VError constructor has several forms:</p>\n<pre><code class=\"language-javascript\">/*\n * This is the most general form.  You can specify any supported options\n * (including \"cause\" and \"info\") this way.\n */\nnew VError(options, sprintf_args...)\n\n/*\n * This is a useful shorthand when the only option you need is \"cause\".\n */\nnew VError(cause, sprintf_args...)\n\n/*\n * This is a useful shorthand when you don't need any options at all.\n */\nnew VError(sprintf_args...)\n</code></pre>\n<p>All of these forms construct a new VError that behaves just like the built-in\nJavaScript <code>Error</code> class, with some additional methods described below.</p>\n<p>In the first form, <code>options</code> is a plain object with any of the following\noptional properties:</p>\n<table>\n<thead>\n<tr>\n<th>Option name</th>\n<th>Type</th>\n<th>Meaning</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><code>name</code></td>\n<td>string</td>\n<td>Describes what kind of error this is.  This is intended for programmatic use to distinguish between different kinds of errors.  Note that in modern versions of Node.js, this name is ignored in the \n<code>stack</code>\n property value, but callers can still use the \n<code>name</code>\n property to get at it.</td>\n</tr>\n<tr>\n<td><code>cause</code></td>\n<td>any Error object</td>\n<td>Indicates that the new error was caused by \n<code>cause</code>\n.  See \n<code>cause()</code>\n below.  If unspecified, the cause will be \n<code>null</code>\n.</td>\n</tr>\n<tr>\n<td><code>strict</code></td>\n<td>boolean</td>\n<td>If true, then \n<code>null</code>\n and \n<code>undefined</code>\n values in \n<code>sprintf_args</code>\n are passed through to \n<code>sprintf()</code>\n.  Otherwise, these are replaced with the strings \n<code>'null'</code>\n, and '\n<code>undefined</code>\n', respectively.</td>\n</tr>\n<tr>\n<td><code>constructorOpt</code></td>\n<td>function</td>\n<td>If specified, then the stack trace for this error ends at function \n<code>constructorOpt</code>\n.  Functions called by \n<code>constructorOpt</code>\n will not show up in the stack.  This is useful when this class is subclassed.</td>\n</tr>\n<tr>\n<td><code>info</code></td>\n<td>object</td>\n<td>Specifies arbitrary informational properties that are available through the \n<code>VError.info(err)</code>\n static class method.  See that method for details.</td>\n</tr>\n</tbody>\n</table>\n<p>The second form is equivalent to using the first form with the specified <code>cause</code>\nas the error's cause.  This form is distinguished from the first form because\nthe first argument is an Error.</p>\n<p>The third form is equivalent to using the first form with all default option\nvalues.  This form is distinguished from the other forms because the first\nargument is not an object or an Error.</p>\n<p>The <code>WError</code> constructor is used exactly the same way as the <code>VError</code>\nconstructor.  The <code>SError</code> constructor is also used the same way as the\n<code>VError</code> constructor except that in all cases, the <code>strict</code> property is\noverriden to `true.</p>\n<h2>Public properties</h2>\n<p><code>VError</code>, <code>WError</code>, and <code>SError</code> all provide the same public properties as\nJavaScript's built-in Error objects.</p>\n<table>\n<thead>\n<tr>\n<th>Property name</th>\n<th>Type</th>\n<th>Meaning</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><code>name</code></td>\n<td>string</td>\n<td>Programmatically-usable name of the error.</td>\n</tr>\n<tr>\n<td><code>message</code></td>\n<td>string</td>\n<td>Human-readable summary of the failure.  Programmatically-accessible details are provided through \n<code>VError.info(err)</code>\n class method.</td>\n</tr>\n<tr>\n<td><code>stack</code></td>\n<td>string</td>\n<td>Human-readable stack trace where the Error was constructed.</td>\n</tr>\n</tbody>\n</table>\n<p>For all of these classes, the printf-style arguments passed to the constructor\nare processed with <code>sprintf()</code> to form a message.  For <code>WError</code>, this becomes\nthe complete <code>message</code> property.  For <code>SError</code> and <code>VError</code>, this message is\nprepended to the message of the cause, if any (with a suitable separator), and\nthe result becomes the <code>message</code> property.</p>\n<p>The <code>stack</code> property is managed entirely by the underlying JavaScript\nimplementation.  It's generally implemented using a getter function because\nconstructing the human-readable stack trace is somewhat expensive.</p>\n<h2>Class methods</h2>\n<p>The following methods are defined on the <code>VError</code> class and as exported\nfunctions on the <code>verror</code> module.  They're defined this way rather than using\nmethods on VError instances so that they can be used on Errors not created with\n<code>VError</code>.</p>\n<h3><code>VError.cause(err)</code></h3>\n<p>The <code>cause()</code> function returns the next Error in the cause chain for <code>err</code>, or\n<code>null</code> if there is no next error.  See the <code>cause</code> argument to the constructor.\nErrors can have arbitrarily long cause chains.  You can walk the <code>cause</code> chain\nby invoking <code>VError.cause(err)</code> on each subsequent return value.  If <code>err</code> is\nnot a <code>VError</code>, the cause is <code>null</code>.</p>\n<h3><code>VError.info(err)</code></h3>\n<p>Returns an object with all of the extra error information that's been associated\nwith this Error and all of its causes.  These are the properties passed in using\nthe <code>info</code> option to the constructor.  Properties not specified in the\nconstructor for this Error are implicitly inherited from this error's cause.</p>\n<p>These properties are intended to provide programmatically-accessible metadata\nabout the error.  For an error that indicates a failure to resolve a DNS name,\ninformational properties might include the DNS name to be resolved, or even the\nlist of resolvers used to resolve it.  The values of these properties should\ngenerally be plain objects (i.e., consisting only of null, undefined, numbers,\nbooleans, strings, and objects and arrays containing only other plain objects).</p>\n<h3><code>VError.fullStack(err)</code></h3>\n<p>Returns a string containing the full stack trace, with all nested errors recursively\nreported as <code>'caused by:' + err.stack</code>.</p>\n<h3><code>VError.findCauseByName(err, name)</code></h3>\n<p>The <code>findCauseByName()</code> function traverses the cause chain for <code>err</code>, looking\nfor an error whose <code>name</code> property matches the passed in <code>name</code> value. If no\nmatch is found, <code>null</code> is returned.</p>\n<p>If all you want is to know <em>whether</em> there's a cause (and you don't care what it\nis), you can use <code>VError.hasCauseWithName(err, name)</code>.</p>\n<p>If a vanilla error or a non-VError error is passed in, then there is no cause\nchain to traverse. In this scenario, the function will check the <code>name</code>\nproperty of only <code>err</code>.</p>\n<h3><code>VError.hasCauseWithName(err, name)</code></h3>\n<p>Returns true if and only if <code>VError.findCauseByName(err, name)</code> would return\na non-null value.  This essentially determines whether <code>err</code> has any cause in\nits cause chain that has name <code>name</code>.</p>\n<h3><code>VError.errorFromList(errors)</code></h3>\n<p>Given an array of Error objects (possibly empty), return a single error\nrepresenting the whole collection of errors.  If the list has:</p>\n<ul>\n<li>0 elements, returns <code>null</code></li>\n<li>1 element, returns the sole error</li>\n<li>more than 1 element, returns a MultiError referencing the whole list</li>\n</ul>\n<p>This is useful for cases where an operation may produce any number of errors,\nand you ultimately want to implement the usual <code>callback(err)</code> pattern.  You can\naccumulate the errors in an array and then invoke\n<code>callback(VError.errorFromList(errors))</code> when the operation is complete.</p>\n<h3><code>VError.errorForEach(err, func)</code></h3>\n<p>Convenience function for iterating an error that may itself be a MultiError.</p>\n<p>In all cases, <code>err</code> must be an Error.  If <code>err</code> is a MultiError, then <code>func</code> is\ninvoked as <code>func(errorN)</code> for each of the underlying errors of the MultiError.\nIf <code>err</code> is any other kind of error, <code>func</code> is invoked once as <code>func(err)</code>.  In\nall cases, <code>func</code> is invoked synchronously.</p>\n<p>This is useful for cases where an operation may produce any number of warnings\nthat may be encapsulated with a MultiError -- but may not be.</p>\n<p>This function does not iterate an error's cause chain.</p>\n<h2>Examples</h2>\n<p>The \"Demo\" section above covers several basic cases.  Here's a more advanced\ncase:</p>\n<pre><code class=\"language-javascript\">var err1 = new VError('something bad happened');\n/* ... */\nvar err2 = new VError({\n    'name': 'ConnectionError',\n    'cause': err1,\n    'info': {\n        'errno': 'ECONNREFUSED',\n        'remote_ip': '127.0.0.1',\n        'port': 215\n    }\n}, 'failed to connect to \"%s:%d\"', '127.0.0.1', 215);\n\nconsole.log(err2.message);\nconsole.log(err2.name);\nconsole.log(VError.info(err2));\nconsole.log(err2.stack);\n</code></pre>\n<p>This outputs:</p>\n<pre><code>failed to connect to \"127.0.0.1:215\": something bad happened\nConnectionError\n{ errno: 'ECONNREFUSED', remote_ip: '127.0.0.1', port: 215 }\nConnectionError: failed to connect to \"127.0.0.1:215\": something bad happened\n    at Object.&#x3C;anonymous> (/home/dap/node-verror/examples/info.js:5:12)\n    at Module._compile (module.js:456:26)\n    at Object.Module._extensions..js (module.js:474:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:312:12)\n    at Function.Module.runMain (module.js:497:10)\n    at startup (node.js:119:16)\n    at node.js:935:3\n</code></pre>\n<p>Information properties are inherited up the cause chain, with values at the top\nof the chain overriding same-named values lower in the chain.  To continue that\nexample:</p>\n<pre><code class=\"language-javascript\">var err3 = new VError({\n    'name': 'RequestError',\n    'cause': err2,\n    'info': {\n        'errno': 'EBADREQUEST'\n    }\n}, 'request failed');\n\nconsole.log(err3.message);\nconsole.log(err3.name);\nconsole.log(VError.info(err3));\nconsole.log(err3.stack);\n</code></pre>\n<p>This outputs:</p>\n<pre><code>request failed: failed to connect to \"127.0.0.1:215\": something bad happened\nRequestError\n{ errno: 'EBADREQUEST', remote_ip: '127.0.0.1', port: 215 }\nRequestError: request failed: failed to connect to \"127.0.0.1:215\": something bad happened\n    at Object.&#x3C;anonymous> (/home/dap/node-verror/examples/info.js:20:12)\n    at Module._compile (module.js:456:26)\n    at Object.Module._extensions..js (module.js:474:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:312:12)\n    at Function.Module.runMain (module.js:497:10)\n    at startup (node.js:119:16)\n    at node.js:935:3\n</code></pre>\n<p>You can also print the complete stack trace of combined <code>Error</code>s by using\n<code>VError.fullStack(err).</code></p>\n<pre><code class=\"language-javascript\">var err1 = new VError('something bad happened');\n/* ... */\nvar err2 = new VError(err1, 'something really bad happened here');\n\nconsole.log(VError.fullStack(err2));\n</code></pre>\n<p>This outputs:</p>\n<pre><code>VError: something really bad happened here: something bad happened\n    at Object.&#x3C;anonymous> (/home/dap/node-verror/examples/fullStack.js:5:12)\n    at Module._compile (module.js:409:26)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Function.Module.runMain (module.js:441:10)\n    at startup (node.js:139:18)\n    at node.js:968:3\ncaused by: VError: something bad happened\n    at Object.&#x3C;anonymous> (/home/dap/node-verror/examples/fullStack.js:3:12)\n    at Module._compile (module.js:409:26)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Function.Module.runMain (module.js:441:10)\n    at startup (node.js:139:18)\n    at node.js:968:3\n</code></pre>\n<p><code>VError.fullStack</code> is also safe to use on regular <code>Error</code>s, so feel free to use\nit whenever you need to extract the stack trace from an <code>Error</code>, regardless if\nit's a <code>VError</code> or not.</p>\n<h1>Reference: MultiError</h1>\n<p>MultiError is an Error class that represents a group of Errors.  This is used\nwhen you logically need to provide a single Error, but you want to preserve\ninformation about multiple underying Errors.  A common case is when you execute\nseveral operations in parallel and some of them fail.</p>\n<p>MultiErrors are constructed as:</p>\n<pre><code class=\"language-javascript\">new MultiError(error_list)\n</code></pre>\n<p><code>error_list</code> is an array of at least one <code>Error</code> object.</p>\n<p>The cause of the MultiError is the first error provided.  None of the other\n<code>VError</code> options are supported.  The <code>message</code> for a MultiError consists the\n<code>message</code> from the first error, prepended with a message indicating that there\nwere other errors.</p>\n<p>For example:</p>\n<pre><code class=\"language-javascript\">err = new MultiError([\n    new Error('failed to resolve DNS name \"abc.example.com\"'),\n    new Error('failed to resolve DNS name \"def.example.com\"'),\n]);\n\nconsole.error(err.message);\n</code></pre>\n<p>outputs:</p>\n<pre><code>first of 2 errors: failed to resolve DNS name \"abc.example.com\"\n</code></pre>\n<p>See the convenience function <code>VError.errorFromList</code>, which is sometimes simpler\nto use than this constructor.</p>\n<h2>Public methods</h2>\n<h3><code>errors()</code></h3>\n<p>Returns an array of the errors used to construct this MultiError.</p>\n<h1>Contributing</h1>\n<p>See separate <a href=\"CONTRIBUTING.html\">contribution guidelines</a>.</p>",docPath:"argo-ci/node_modules/verror/readme",proj:"argo-ci"}}}});
//# sourceMappingURL=path---docs-argo-ci-node-modules-verror-readme-html-f4fd108f2fb78b3a2059.js.map